# Generated by Django 5.1.4 on 2025-01-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tooltip',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='myapp.category', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
